### ISSUE TITLE
Get list of messages from a complex JSON file

### ISSUE THREAD

**Issue by rsacherer** [zeroSteiner/rule-engine#101]
Hi, I have a hard time to create a rule to get all `message` texts from all checks:
```
rule > report.health
result: 
{
  "status": "HEALTH_ERR",
  "checks": {
    "MGR_MODULE_ERROR": {
      "severity": "HEALTH_ERR",
      "summary": {
        "message": "Module 'devicehealth' has failed: cannot start a transaction within a transaction",
        "count": "1"
      },
      "detail": [
        {
          "message": "Module 'devicehealth' has failed: cannot start a transaction within a transaction"
        }
      ],
      "muted": false
    }
  },
  "mutes": []
}
```

In the end if only one detail message exists as in the above example, I'd like to only get a tuple like:
("Module 'devicehealth' has failed: cannot start a transaction within a transaction",)

But if I would have multiple messages and possible multiple checks then I want them all in the tuple. 

I am struggling to get that back, would appreciate any help about that. 

Thanks
Raimund

**Comment by rsacherer** [comment]
What I came up with, but that unfortunately has the indices hard coded:
```
rule > [ x for x in [report.health.checks[check] for check in report.health.checks]][0]['detail'][0]['message']
result: 
"Module 'devicehealth' has failed: cannot start a transaction within a transaction"
```

**Comment by zeroSteiner** [comment]
Maybe something like `[ [ detail.values for detail in check_val['detail'] ] for check_val in [report.health.checks[check_key] for check_key in report.health.checks ] ]`

If that doesn't work for you, can you please clarify your question by replacing the two instances of `"Module 'devicehealth' has failed: cannot start a transaction within a transaction"` with unique strings in your input and example to better illustrate the desired outcome?

**Comment by rsacherer** [comment]
Thanks, I came up with a good way to get the data, it's hard to wrap my head around it, but I'm getting accustomed to it.

:-)
