### ISSUE TITLE
Arithmetic comparison with None/null types

### ISSUE THREAD

**Issue by aaditya-panik** [zeroSteiner/rule-engine#13]
Hi @zeroSteiner,

I had a question regarding how I can handle cases in which there are arithmetic comparisons (Or more generally speaking, any operations) with NoneTypes. For example, what is the expected behaviour here
```python
rule_engine.Rule('a > 10').matches({'a': None})
```

This results in an exception
```python
rule_engine.errors.EvaluationError: data type mismatch
```
but I was wondering if there is a way of suppressing that and evaluating it to `False`.

BTW, great project and looking forward to future features especially support for sets, kudos! :+1:

**Comment by zeroSteiner** [comment]
You could use the ternary operator, which I'm realizing now isn't particularly well documented. That would make this `Rule('(a == null ? 0 : a) > 10').matches({'a': None})`. You could also check that it's not `null` before doing the arithmetic comparison like `Rule('a != null and a > 10').matches({'a': None})`.

That's a little bit clunky though. My suggestion to make it easier for your rule writers is to normalize `a` in Python prior to evaluating the rule like `rule_engine.Rule('a > 10').matches({'a': a or 0})`.

**Comment by aaditya-panik** [comment]
Got it, thanks. I was hoping there was a way to evaluate expressions even if there was a type mismatch. I guess even if there would be, it would nullify the expression which is as good as handling the exception and evaluating the expression to None.

**Comment by qaiken** [comment]
I know this is an old thread but it would be nice to see this still evaluate / not throw: `rule_engine.Rule('a > 10 or b < 25').matches({'a': None, 'b': 20})`

**Comment by zeroSteiner** [comment]
Best I'd be willing to do is add a `to_flt` / `to_int` attribute to the NULL datatype so you could explicitly convert it to 0. Implicitly treating NULL as 0 is a little too close to javascript for my taste.

**Comment by zeroSteiner** [comment]
From what I can see it's working as intended. The left expression is evaluated first which results in one of three outcomes:

1. The expression throws an error and execution of the entire rule is terminated. An exception is thrown which must be caught by the Python caller.
2. The expression evaluates to `false`, so the execution continues to the right expression.
3. The expression evaluates to true, and execution of the `or` expression is terminated. There's no need to evaluate what's on the right, and for the sake of efficiency, it shouldn't evaluate things that are unnecessary. You can observe the same behavior in Python using an expression that triggers a `ZeroDivisionError` as an example.


```python
In [8]: True or 1 / 0
Out[8]: True

In [9]: 1 / 0 or True
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
Cell In[9], line 1
----> 1 1 / 0 or True

ZeroDivisionError: division by zero
```

**Comment by qaiken** [comment]
fair enough, I very much appreciate the quick feedback and thoughts here!
