### ISSUE TITLE
Arithmetic expressions with powers

### ISSUE THREAD

**Issue by aaditya-panik** [zeroSteiner/rule-engine#20]
Hi @zeroSteiner 

I was going through some expressions and noticed something for arithmetic expressions using powers. The parser parses powers as a `float` type (mostly because it uses the `math.pow` method) versus other operators which which result in `decimal.Decimal`.

https://github.com/zeroSteiner/rule-engine/blob/7a48664ddbfabf7a8aa9b544eab0e9eccda029e0/lib/rule_engine/ast.py#L779

this results in `TypeError: unsupported operand type(s) for /: 'decimal.Decimal' and 'float'`.

I think this can be resolved by using [`operator.pow`](https://docs.python.org/3/library/operator.html#operator.pow) instead of [`math.pow`.](https://docs.python.org/3/library/math.html#math.pow)

To recreate the error,

```
python -m rule_engine.debug_repl --edit-console
edit the 'context' and 'thing' objects as necessary
>>> thing = dict(a=8.0,b=2.0)
>>> exit()
exiting the edit console...
rule > a/(b**2)
TypeError: unsupported operand type(s) for /: 'decimal.Decimal' and 'float'
```

**Comment by zeroSteiner** [comment]
Fixed in commit e229063be8e53f6de9790a66354a75d24510e640 which has been released in v3.1.2 and pushed to [PyPi](https://pypi.org/project/rule-engine/3.1.2/).
