### ISSUE TITLE
Key existing rule

### ISSUE THREAD

**Issue by aviad-ariel** [zeroSteiner/rule-engine#33]
Is there any way i can base a rule on the existence of a key?
I'm fetching data from external api and i want to implement a rule that checks if a key is exist in it
Let's say for example that i received the following data:
```
{
    "name": "example",
    "description": "rule-engine is great"
}
```
I want a rule that will return true if `reference` is in this data and false otherwise.
In every way that i tried to implement it i came up with `rule_engine.errors.SymbolResolutionError: reference` (obviously).

Thanks in advance

**Comment by zeroSteiner** [comment]
There are two ways you can do that.

# Response Object
If your "thing" is wrapped in a response object, then you can just use the `in` operator. You'd need to access everything as a key off of the API response in this way though.

```
python3 -m rule_engine.debug_repl --edit-console
edit the 'context' and 'thing' objects as necessary
>>> thing = {'response': {'name': 'example', 'description': 'rule-engine is great'}}
>>> exit()
exiting the edit console...
rule > 'reference' in response
result: 
False
rule > 'name' in response
result: 
True
rule > response['name']
result: 
'example'
rule >
```

# Default Value
Alternatively, you can update the execution context and define a default value, `null` would probably be your best bet. This would keep the other keys at the top-level namespace. Doing it this way basically makes the default value `null` for every undefined symbol.

```
python3 -m rule_engine.debug_repl --edit-console
edit the 'context' and 'thing' objects as necessary
>>> thing = {'name': 'example', 'description': 'rule-engine is great'}
>>> context.default_value
UNDEFINED
>>> context.default_value = None
>>> exit()
exiting the edit console...
rule > name
result: 
'example'
rule > reference == null
result: 
True
```

# Define The Value
Finally, if your type resolver is the default getitem one, which I'm guessing it is if you're working with API responses that are dictionaries, you could provide and merge a set of default values.

That would make it something like this:
```
defaults = {'references': None}
rule.matches({**defaults, **api_response})
```
