### ISSUE TITLE
Datetime operations and Timedeltas

### ISSUE THREAD

**Issue by djmattyg007** [zeroSteiner/rule-engine#40]
According to the documentation, there doesn't seem to be any support for timedeltas, or any mathematical operations on datetime objects. This would be super useful for implementing rules such as "older than 30 days" without having to calculate what "30 days before now" is manually.

For example, ideally I could write a rule that looks like this to implement the above:

```
created_at < now - P30D
```

**Comment by djmattyg007** [comment]
Right now, I would have to manually calculate what `now - 30 days` is and embed it in the rule string. This may not be feasible if the rule is being specified as static configuration, outside of code.

**Comment by djmattyg007** [comment]
Unfortunately `python-dateutil` still doesn't yet support duration parsing. You might want to consider migrating to `isodate`, which does:

https://github.com/gweis/isodate

**Comment by zeroSteiner** [comment]
See discussion #18.

**Comment by djmattyg007** [comment]
@zeroSteiner I wasn't aware of that discussion. Since I filed that issue, I've actually started work on adding support for a timedelta type. The changes are going well so far - would you accept it as a PR?

**Comment by zeroSteiner** [comment]
Possibly, depending on how it was implemented. I was hoping to avoid adding another data type because that's a lot of work to build out, document, test and maintain, but I'm not sure how else you'd do it.
