### ISSUE TITLE
How to Run a list of Rules

### ISSUE THREAD

**Issue by TOttun** [zeroSteiner/rule-engine#45]
If I had a list of rules how do I run them altogether 

e.g 

rule_1 = rule_engine.Rule(
    'vehicle_type == "minibus" or vehicle_type == "bus" or vehicle_type == "coach" and relation_to_claim == "Passenger" and injured_physical == "True" and party_id == driver_id', context=context
)

rule_2= rule_engine.Rule(
    'no_injuries_at_fnol == "True" and injured_physical == "True"', context=context
)

rule_3 = rule_engine.Rule(
    'occupation =~ "taxi driver\w+" or occupation =~ "private hire driver\w+" and vehicle_usage =~ "taxi driver\w+" or vehicle_usage =~ "private hire driver\w+" and third_party == "True"', context=context
)

against a dataset

**Comment by zeroSteiner** [comment]
Use a combination of logical operators and list comprehension.

**Comment by TOttun** [comment]
> 

do you have an example ? 

my idea was having all the rules in a list and then for each rule in the rules list run it against a data

**Comment by zeroSteiner** [comment]
That sounds good, go ahead and do it that way.
