### ISSUE TITLE
Is it possible to have a function within a rule or call a function in a rule ?

### ISSUE THREAD

**Issue by TOttun** [zeroSteiner/rule-engine#46]
For example;

import datetime

def time_in_range(start, end, current):
"""Returns whether current is in the range [start, end]"""
return start <= current <= end
start = datetime.time(0, 0, 0)
end = datetime.time(23, 55, 0)
current = datetime.datetime.now().time()
print(time_in_range(start, end, current))

Can I call this function in a rule ? or can I make it into a rule ?

**Comment by zeroSteiner** [comment]
See #32. There is no function support at this time. Having said that, you can do time comparisons with the built in data types. See https://zerosteiner.github.io/rule-engine/types.html#datetime-and-timedelta
