### ISSUE TITLE
Rule compare

### ISSUE THREAD

**Issue by scainet** [zeroSteiner/rule-engine#48]
May be interesting make Rule comparison

```python
r1 = rule_engine.Rule("a == 'HELLO' and b == 'BYE'")
r2 = rule_engine.Rule("b == 'BYE' and a == 'HELLO'")
r1 == r2
True
```

**Comment by zeroSteiner** [comment]
Those aren't the same though due to the order of operations. You could just compare the rule text but that wouldn't account for internal white space like `a == 1` and `a ==      1`.

I'm not sure I see the use case here.

**Comment by zeroSteiner** [comment]
What would the use case be for this?

**Comment by 0ge** [comment]
I would be interested in this.

My use case is the following: I have a list of tuples containing a rule and an action. If there are two matching rules, only the first action will be executed.

As a sanity check I would like to iterate over the rules to identify rules that would never be evaluated. Something like this:

```python
r1 = rule_engine.Rule("a == 'HELLO'")
r2 = rule_engine.Rule("a == 'HELLO' and b == 'WORLD'")

if r1 > r2:
     print("Warning: Rule `r2` will never be evaluated.")
```

(Not sure the normal comparison operators are very intuitive here)
