### ISSUE TITLE
Bad behaviour with wrong rule that does not make errors and returns bad results

### ISSUE THREAD

**Issue by Merlain** [zeroSteiner/rule-engine#54]
Hello,

While writing rules, I realized the following result when I wrote "int_variable==01" instead of "int_variable==1".

When this condition is the only one in the rule, I get an error but when it is followed by other conditions, there is no more error and the returned results are invalid.

The results are invalid because what is before this condition does not seem to be taken into account.

Here is an example:

``` python3
import rule_engine

data = {'other': 'other', 'test': 'test', 'count':1}

# Invalid rule that raise an error
rule_str = "count==01"
rule = rule_engine.Rule(rule_str) # Return an error

# Invalid rule that does not return an error
rule_str = "test=='NOTTEST' and count==01 and other=='other'"
rule = rule_engine.Rule(rule_str)

rule.matches(data) # True
```

In this case, the "test=='NOTTEST' " part is ignored because before the invalid condition (the invalid condition is also ignored).

**Comment by zeroSteiner** [comment]
Yeah, something is wrong here. I'm pretty sure it has to do with the `01` literal. I'm able to reproduce the unexpected behavior you're seeing and I've got what I need to look into this further.

Thanks for reporting this.

**Comment by zeroSteiner** [comment]
Fixed in commit 055dbfaeda51228223c16dc6bf54747524037dcf. I'll publish version 3.5.1 to PyPi with this fix this weekend.

**Comment by Merlain** [comment]
Thank you ! awsome !

**Comment by zeroSteiner** [comment]
Version 3.5.1 has been published to PyPi with this fix. https://pypi.org/project/rule-engine/3.5.1/
