### ISSUE TITLE
Support `sum`

### ISSUE THREAD

**Issue by n-chatchai** [zeroSteiner/rule-engine#58]
Given,

```
scores = [
  {"name": "do x": "score": 10},
  {"name": "do 7": "score": 10},
]
```

If it is possible to support rule like

sum([score['score'] for score in scores])  > 10
or,
[score['score'] for score in scores].sum > 10

Thank you,

**Comment by zeroSteiner** [comment]
No there's no `sum` attribute and there is no function support (see #32).
