### ISSUE TITLE
Raise regex failure details

### ISSUE THREAD

**Issue by zeroSteiner** [zeroSteiner/rule-engine#61]
While looking at #59 I noticed that there aren't any details shown when there's a regex failure. The details should be propagated so the user can see why the regex is invalid. The regex itself should also probably be included in the exception for inspection.

Integrate this into the debug repl with exception handling to print those details for debugging purposes.

**Comment by tianguoxin** [comment]
Best Wishes

**Comment by zeroSteiner** [comment]
Completed in v3.6.
