### ISSUE TITLE
Is it possible to access str key with dot?

### ISSUE THREAD

**Issue by nicolas-rdgs** [zeroSteiner/rule-engine#64]
Is it possible to use a key with a dot instead of trying to browse a dictionary? For example:

```python
r = rule_engine.Rule("field_1=='aze' and result.field_2 == 'qsd'")
in = {"field_1": "aze", "result.field_2": "qsd"}

r.matches(in)
SymbolResolutionError: result
``` 

I tried `'result.field_2' == \"qsd\"` but I think it's interpreted as a string instead to use the key name "result.field_2".

We received some flat JSON, so what's the best way to do it?

**Comment by zeroSteiner** [comment]
No because a period is parsed as the get attribute operator. You could pass your object in as a dictionary then access the keys using strings containing the period.

Something like: `rule.evaluate({ 'json': record })`

Then: `json['result.value']`
