### ISSUE TITLE
Critical issue - No attribute Builtins 

### ISSUE THREAD

**Issue by priyankmav** [zeroSteiner/rule-engine#67]
I noticed a critical issue in 4.0.0 - after the upgrade, we noticed that we lost existing functionality of the rule engine, and we are seeing this error while rule engine is executed.
`module 'rule_engine.engine' has no attribute 'Builtins'
`

**Comment by zeroSteiner** [comment]
It was moved to the builtins module. I'll update the change log to note that as a breaking change with the others.
