### ISSUE TITLE
Enhance Min/Max function

### ISSUE THREAD

**Issue by jinqinn** [zeroSteiner/rule-engine#69]
Example:
```
age = 18
rule1 = rule_engine.Rule("$min(age, 21, 20)")
rule2 = rule_engine.Rule("$max(age, 20, 19)")
```

**Comment by zeroSteiner** [comment]
I don't understand what this ticket is trying to say. The usage of `$min` and `$max` is incorrect however. Both functions take an array of floats, not multiple float arguments.

```
rule > $min([1, 2, 3])
result: 
Decimal('1')
rule > 
```

Please clarify your request.

**Comment by jinqinn** [comment]
i am so sorry, my english is poor. 
i want to use Min funcation that supports multiple float arguments, and now i got a workground:
`
age = 18
min = sys.min
rule1 = rule_engine.Rule("min(age, 19, 20)")
`
it will output 18.
