### ISSUE TITLE
Comprehension Expression Error

### ISSUE THREAD

**Issue by zeroSteiner** [zeroSteiner/rule-engine#72]
how can i add any or all condition  for a list of dictionaries.
something like this
$all( [ item['model'] == 'oncology' for item in api_response ])

_Originally posted by @MdTabraiz in https://github.com/zeroSteiner/rule-engine/discussions/16#discussioncomment-6624007_

when i am doing something like this i am getting the following error:
can not map python type 'ComprehensionExpression' to a compatible data type

**Comment by zeroSteiner** [comment]
Fixed in commit cca88d6. The issue was the expression check to propagate the `result_type` was too restrictive. I remember seeing this and meaning to fix it but it must have slipped my mind. Anyways, it's fixed now and released in 4.1.0.

**Comment by MdTabraiz** [comment]
Thanks for the quick action.
