### ISSUE TITLE
Adding Pandas Dataframe as Datatype?

### ISSUE THREAD

**Issue by PascalStehling** [zeroSteiner/rule-engine#84]
Hi,

firstly, thanks for the nice work so far, just found this yesterday :)

I really like the Idea of having a query engine to filter through piles of tabular data (like CSV). The Problem is that the performance gets quite bad if the data is big enough and there are alot of rules. (In my case as Data Engineer, 100.000 to millions of rows and multiple dozens of rules).

So I was thinking if it would be useful to integrated [pandas](https://pandas.pydata.org/pandas-docs/stable/index.html) (the defacto dataframe standard for python) to your query engine. With that alot of operations could be run not just simply on each row via a dict, but on the whole column at once, via vectorization.

I played a little with you Code and got a very simple version working (see screenshot), with just some operators (just equal, not equal, and, or)

![image](https://github.com/zeroSteiner/rule-engine/assets/33455644/59a3964a-c08a-4683-a7cc-555212874492)

The resulting array of bools can be used directly on the dataframe to just get the rows that are needed or perform other work.

I also performed a small benchmark with 400.000 rows and as the results show a speedup of more then 30.000 times. (see second screenshot)

![image](https://github.com/zeroSteiner/rule-engine/assets/33455644/4bb7c2e6-cd5e-48c9-a622-a8b7527c12cb)

Now to my question, are you interested in some implementation like this? If so are you willing to do it, otherwise I can also try (still need to understand the Codebase better, only worked for ~2 hrs or so on it) and make a pull request when Im finished if this ok with you and you have time/interest to review it and help to improve it. Also if you see some major problems in doing it, please tell me.

Function wise, nearly everything that you can do with the current types, can also be done with pandas. There are also methods for string search on whole arrays and stuff like that.

Thanks for reading until the End and have a nice day
Best Pascal :)

**Comment by zeroSteiner** [comment]
I would potentially be interested in this. I don't personally use Pandas but I've definitely heard of it and I can understand the value in performance and compatibility with such a popular library.

It doesn't exactly sound like this would truly be a new rule engine data type, those are a lot of work to write. It sounds like this would likely involve some updates in key places to allow mapping Pandas values as inputs as native Python values currently are.

Would you mind sharing the edits you've made just far in a patch, a draft PR or something so I could take a look at the direction you took to achieve the performance improvements you've already shown?

**Comment by PascalStehling** [comment]
I created a draft PR :)

For alot of operands it should be fairly trivial to put it in. You opinion on the code provided would really interest me.

**Comment by zeroSteiner** [comment]
Thanks for sending it to me. I'll try and take some time to review in this weekend.
