### ISSUE TITLE
No attribute Rule

### ISSUE THREAD

**Issue by huuhuannt1998** [zeroSteiner/rule-engine#88]
I have trying the following example:

```
import rule_engine
import datetime

comics = [
  {
    'title': 'Batman',
    'publisher': 'DC',
    'issue': 89,
    'released': datetime.date(2020, 4, 28)
  },
  {
    'title': 'Flash',
    'publisher': 'DC',
    'issue': 753,
    'released': datetime.date(2020, 5, 5)
  },
  {
    'title': 'Captain Marvel',
    'publisher': 'Marvel',
    'issue': 18,
    'released': datetime.date(2020, 5, 6)
  }
]


rule = rule_engine.Rule(
  # match books published by DC
  'publisher == "DC"'
)

# check if the first object matches
print(rule.matches(comics[0])) # => True

# filter the iterable "comics" and return matching objects
print(rule.filter(comics)) # => <generator object Rule.filter at 0x7f2bdafbe650>
```

I got this error "AttributeError: partially initialized module 'rule_engine' has no attribute 'Rule' (most likely due to a circular import)".  How do I get this fixed?

**Comment by huuhuannt1998** [comment]
That is the name of my python file.

**Comment by zeroSteiner** [comment]
Try changing it to anything else. You're defining the `rule_engine` module yourself and not defining the `Rule` class. Rename it to `test.py` or something else.

**Comment by huuhuannt1998** [comment]
> Try changing it to anything else. You're defining the `rule_engine` module yourself and not defining the `Rule` class. Rename it to `test.py` or something else.

It works. Thanks for your help.
