### ISSUE TITLE
String to Integer casting

### ISSUE THREAD

**Issue by cah-rohithkarnati** [zeroSteiner/rule-engine#9]
My required condition -> '**to_integer**(some_column) > 180'

Unfortunately the I am receiving **_source_column_** as a string data and do not want to put the casting logic in python directly in code. I am planning to put the conditions on the json where I am trying to store the condition and syphoning those from the code.

Please advise how I can implement the saem.

**Comment by zeroSteiner** [comment]
Version 2.3 [added](https://zerosteiner.github.io/rule-engine/change_log.html#version-2-3-0) `to_flt` and `to_int` attributes for casting strings. Try `some_column.to_int > 180`, that should do the trick.

**Comment by cah-rohithkarnati** [comment]
Worked like a charms!!!
Thanks. Great job though. Having fun using the lib.
It would be great if you could point me towards the documentation, if any for these neat tricks.

**Comment by zeroSteiner** [comment]
Great, I'm glad that worked for you. Check out the [Getting Started](https://zerosteiner.github.io/rule-engine/getting_started.html) docs. There's quite abit of usage information in there.
